ALTER TABLE public.ongs
  ADD COLUMN IF NOT EXISTS missao TEXT,
  ADD COLUMN IF NOT EXISTS area_atuacao VARCHAR(100),
  ADD COLUMN IF NOT EXISTS site VARCHAR(255),
  ADD COLUMN IF NOT EXISTS instagram VARCHAR(100),
  ADD COLUMN IF NOT EXISTS img_capa VARCHAR(500);